[package]
name = "CodinGame-Mad-Pod-Racing"
description = "Code for the Mad Pod Racing game"
authors = ["Dominique Roth <dominik@roth.systems>"]
homepage = "https://roth.systems/"
repository = "https://github.com/Dom-Roth/CodinGame"
version = "0.1.0"
edition = "2021"

[dependencies]
